### ISSUE TITLE
check what's wrong with travis

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/provent#2]
It's not triggering when I push to master

:(

**Comment by raphaelfabeni** [comment]
:cry:

**Comment by mauriciosoares** [comment]
Hell yeah! its working now.

Just switched branches and pushed, and now everything is wokring.

Maybe it was cache or some shit like that

<img width="279" alt="screen shot 2015-07-20 at 13 03 42" src="https://cloud.githubusercontent.com/assets/2321259/10136160/6fb5d350-65c9-11e5-842a-0a488817c8d0.png">

**Comment by raphaelfabeni** [comment]
![crazy](https://media.giphy.com/media/MdeeTvpn7g1pu/giphy.gif)
